# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inventory.ui'
#
# Created: Fri Aug 02 17:49:00 2013
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1057, 638)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.mainLayout = QtGui.QVBoxLayout()
        self.mainLayout.setSpacing(6)
        self.mainLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.mainLayout.setObjectName(_fromUtf8("mainLayout"))
        self.numberingLayout = QtGui.QHBoxLayout()
        self.numberingLayout.setObjectName(_fromUtf8("numberingLayout"))
        self.eyeglassesNum = QtGui.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.eyeglassesNum.setFont(font)
        self.eyeglassesNum.setMinimum(1)
        self.eyeglassesNum.setMaximum(1000000)
        self.eyeglassesNum.setProperty("value", 1)
        self.eyeglassesNum.setObjectName(_fromUtf8("eyeglassesNum"))
        self.numberingLayout.addWidget(self.eyeglassesNum)
        self.newButton = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.newButton.setFont(font)
        self.newButton.setObjectName(_fromUtf8("newButton"))
        self.numberingLayout.addWidget(self.newButton)
        self.saveButton = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.saveButton.setFont(font)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.numberingLayout.addWidget(self.saveButton)
        self.status = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.status.setFont(font)
        self.status.setObjectName(_fromUtf8("status"))
        self.numberingLayout.addWidget(self.status)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.numberingLayout.addItem(spacerItem)
        self.mainLayout.addLayout(self.numberingLayout)
        self.eyesLayout = QtGui.QHBoxLayout()
        self.eyesLayout.setObjectName(_fromUtf8("eyesLayout"))
        self.rightEyeGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.rightEyeGroupBox.setObjectName(_fromUtf8("rightEyeGroupBox"))
        self.gridLayout_7 = QtGui.QGridLayout(self.rightEyeGroupBox)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.rightEyeLayout = QtGui.QGridLayout()
        self.rightEyeLayout.setObjectName(_fromUtf8("rightEyeLayout"))
        self.label_2 = QtGui.QLabel(self.rightEyeGroupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.rightEyeLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.rightEyeGroupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.rightEyeLayout.addWidget(self.label_5, 0, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.rightEyeGroupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.rightEyeLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.rAxisSpin = angleSpinBox(self.rightEyeGroupBox)
        self.rAxisSpin.setMinimum(5)
        self.rAxisSpin.setMaximum(180)
        self.rAxisSpin.setSingleStep(5)
        self.rAxisSpin.setObjectName(_fromUtf8("rAxisSpin"))
        self.rightEyeLayout.addWidget(self.rAxisSpin, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.rightEyeGroupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.rightEyeLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.rLinkCheckbox = QtGui.QCheckBox(self.rightEyeGroupBox)
        self.rLinkCheckbox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.rLinkCheckbox.setObjectName(_fromUtf8("rLinkCheckbox"))
        self.rightEyeLayout.addWidget(self.rLinkCheckbox, 2, 3, 1, 1)
        self.rAddSpin = dotSpinBox(self.rightEyeGroupBox)
        self.rAddSpin.setObjectName(_fromUtf8("rAddSpin"))
        self.rightEyeLayout.addWidget(self.rAddSpin, 1, 3, 1, 1)
        self.rCylSpin = QtGui.QDoubleSpinBox(self.rightEyeGroupBox)
        self.rCylSpin.setObjectName(_fromUtf8("rCylSpin"))
        self.rightEyeLayout.addWidget(self.rCylSpin, 1, 1, 1, 1)
        self.rSphereSpin = dotSpinBox(self.rightEyeGroupBox)
        self.rSphereSpin.setObjectName(_fromUtf8("rSphereSpin"))
        self.rightEyeLayout.addWidget(self.rSphereSpin, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.rightEyeLayout, 0, 0, 1, 1)
        self.eyesLayout.addWidget(self.rightEyeGroupBox)
        self.leftEyeGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.leftEyeGroupBox.setObjectName(_fromUtf8("leftEyeGroupBox"))
        self.gridLayout_8 = QtGui.QGridLayout(self.leftEyeGroupBox)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.leftEyeLayout = QtGui.QGridLayout()
        self.leftEyeLayout.setObjectName(_fromUtf8("leftEyeLayout"))
        self.label_8 = QtGui.QLabel(self.leftEyeGroupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.leftEyeLayout.addWidget(self.label_8, 0, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.leftEyeGroupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.leftEyeLayout.addWidget(self.label_9, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.leftEyeGroupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.leftEyeLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.lAxisSpin = angleSpinBox(self.leftEyeGroupBox)
        self.lAxisSpin.setMinimum(5)
        self.lAxisSpin.setMaximum(180)
        self.lAxisSpin.setSingleStep(5)
        self.lAxisSpin.setObjectName(_fromUtf8("lAxisSpin"))
        self.leftEyeLayout.addWidget(self.lAxisSpin, 1, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.leftEyeGroupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.leftEyeLayout.addWidget(self.label_7, 0, 3, 1, 1)
        self.lLinkCheckbox = QtGui.QCheckBox(self.leftEyeGroupBox)
        self.lLinkCheckbox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lLinkCheckbox.setObjectName(_fromUtf8("lLinkCheckbox"))
        self.leftEyeLayout.addWidget(self.lLinkCheckbox, 2, 3, 1, 1)
        self.lSphereSpin = dotSpinBox(self.leftEyeGroupBox)
        self.lSphereSpin.setObjectName(_fromUtf8("lSphereSpin"))
        self.leftEyeLayout.addWidget(self.lSphereSpin, 1, 0, 1, 1)
        self.lCylSpin = negativeZeroSpinBox(self.leftEyeGroupBox)
        self.lCylSpin.setObjectName(_fromUtf8("lCylSpin"))
        self.leftEyeLayout.addWidget(self.lCylSpin, 1, 1, 1, 1)
        self.lAddSpin = dotSpinBox(self.leftEyeGroupBox)
        self.lAddSpin.setObjectName(_fromUtf8("lAddSpin"))
        self.leftEyeLayout.addWidget(self.lAddSpin, 1, 3, 1, 1)
        self.gridLayout_8.addLayout(self.leftEyeLayout, 0, 0, 1, 1)
        self.eyesLayout.addWidget(self.leftEyeGroupBox)
        self.mainLayout.addLayout(self.eyesLayout)
        self.otherLayout = QtGui.QHBoxLayout()
        self.otherLayout.setObjectName(_fromUtf8("otherLayout"))
        self.optionsLayout = QtGui.QVBoxLayout()
        self.optionsLayout.setObjectName(_fromUtf8("optionsLayout"))
        self.addGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.addGroupBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addGroupBox.sizePolicy().hasHeightForWidth())
        self.addGroupBox.setSizePolicy(sizePolicy)
        self.addGroupBox.setObjectName(_fromUtf8("addGroupBox"))
        self.gridLayout_9 = QtGui.QGridLayout(self.addGroupBox)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.addLayout = QtGui.QVBoxLayout()
        self.addLayout.setObjectName(_fromUtf8("addLayout"))
        self.addRadioP = QtGui.QRadioButton(self.addGroupBox)
        self.addRadioP.setChecked(True)
        self.addRadioP.setObjectName(_fromUtf8("addRadioP"))
        self.addLayout.addWidget(self.addRadioP)
        self.addRadioBF = QtGui.QRadioButton(self.addGroupBox)
        self.addRadioBF.setObjectName(_fromUtf8("addRadioBF"))
        self.addLayout.addWidget(self.addRadioBF)
        self.addRadioTF = QtGui.QRadioButton(self.addGroupBox)
        self.addRadioTF.setObjectName(_fromUtf8("addRadioTF"))
        self.addLayout.addWidget(self.addRadioTF)
        self.gridLayout_9.addLayout(self.addLayout, 1, 0, 1, 1)
        self.optionsLayout.addWidget(self.addGroupBox)
        self.childGroupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.childGroupBox.sizePolicy().hasHeightForWidth())
        self.childGroupBox.setSizePolicy(sizePolicy)
        self.childGroupBox.setObjectName(_fromUtf8("childGroupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.childGroupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.childLayout = QtGui.QHBoxLayout()
        self.childLayout.setObjectName(_fromUtf8("childLayout"))
        self.childRadioNo = QtGui.QRadioButton(self.childGroupBox)
        self.childRadioNo.setChecked(True)
        self.childRadioNo.setObjectName(_fromUtf8("childRadioNo"))
        self.childLayout.addWidget(self.childRadioNo)
        self.childRadioYes = QtGui.QRadioButton(self.childGroupBox)
        self.childRadioYes.setObjectName(_fromUtf8("childRadioYes"))
        self.childLayout.addWidget(self.childRadioYes)
        self.gridLayout_5.addLayout(self.childLayout, 3, 0, 1, 1)
        self.optionsLayout.addWidget(self.childGroupBox)
        self.solarGroupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.solarGroupBox.sizePolicy().hasHeightForWidth())
        self.solarGroupBox.setSizePolicy(sizePolicy)
        self.solarGroupBox.setObjectName(_fromUtf8("solarGroupBox"))
        self.gridLayout_6 = QtGui.QGridLayout(self.solarGroupBox)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.solarLayout = QtGui.QHBoxLayout()
        self.solarLayout.setObjectName(_fromUtf8("solarLayout"))
        self.solarRadioNo = QtGui.QRadioButton(self.solarGroupBox)
        self.solarRadioNo.setChecked(True)
        self.solarRadioNo.setObjectName(_fromUtf8("solarRadioNo"))
        self.solarLayout.addWidget(self.solarRadioNo)
        self.solarRadioYes = QtGui.QRadioButton(self.solarGroupBox)
        self.solarRadioYes.setObjectName(_fromUtf8("solarRadioYes"))
        self.solarLayout.addWidget(self.solarRadioYes)
        self.gridLayout_6.addLayout(self.solarLayout, 0, 0, 1, 1)
        self.optionsLayout.addWidget(self.solarGroupBox)
        self.otherLayout.addLayout(self.optionsLayout)
        self.commentLayout = QtGui.QVBoxLayout()
        self.commentLayout.setObjectName(_fromUtf8("commentLayout"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.commentLayout.addWidget(self.label_10)
        self.commentEdit = QtGui.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commentEdit.sizePolicy().hasHeightForWidth())
        self.commentEdit.setSizePolicy(sizePolicy)
        self.commentEdit.setTabChangesFocus(True)
        self.commentEdit.setObjectName(_fromUtf8("commentEdit"))
        self.commentLayout.addWidget(self.commentEdit)
        self.otherLayout.addLayout(self.commentLayout)
        self.mainLayout.addLayout(self.otherLayout)
        self.tableView = QtGui.QTableView(self.centralwidget)
        self.tableView.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tableView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setVisible(False)
        self.tableView.verticalHeader().setStretchLastSection(False)
        self.mainLayout.addWidget(self.tableView)
        self.gridLayout_3.addLayout(self.mainLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1057, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.fileMenu = QtGui.QMenu(self.menubar)
        self.fileMenu.setObjectName(_fromUtf8("fileMenu"))
        MainWindow.setMenuBar(self.menubar)
        self.newAction = QtGui.QAction(MainWindow)
        self.newAction.setObjectName(_fromUtf8("newAction"))
        self.saveAction = QtGui.QAction(MainWindow)
        self.saveAction.setObjectName(_fromUtf8("saveAction"))
        self.exitAction = QtGui.QAction(MainWindow)
        self.exitAction.setObjectName(_fromUtf8("exitAction"))
        self.fileMenu.addAction(self.newAction)
        self.fileMenu.addAction(self.saveAction)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.exitAction)
        self.menubar.addAction(self.fileMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Eyeglasses inventory", None, QtGui.QApplication.UnicodeUTF8))
        self.newButton.setText(QtGui.QApplication.translate("MainWindow", "Nouvelle paire de lunettes", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("MainWindow", "Sauvegarder", None, QtGui.QApplication.UnicodeUTF8))
        self.status.setText(QtGui.QApplication.translate("MainWindow", "Empty", None, QtGui.QApplication.UnicodeUTF8))
        self.rightEyeGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Œil Droit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Sphere", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Addition", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Axe", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Cylindre", None, QtGui.QApplication.UnicodeUTF8))
        self.rLinkCheckbox.setText(QtGui.QApplication.translate("MainWindow", "Lié", None, QtGui.QApplication.UnicodeUTF8))
        self.leftEyeGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Œil Gauche", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Axe", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Cylindre", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Sphere", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Addition", None, QtGui.QApplication.UnicodeUTF8))
        self.lLinkCheckbox.setText(QtGui.QApplication.translate("MainWindow", "Lié", None, QtGui.QApplication.UnicodeUTF8))
        self.addGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Addition", None, QtGui.QApplication.UnicodeUTF8))
        self.addRadioP.setText(QtGui.QApplication.translate("MainWindow", "Progressif", None, QtGui.QApplication.UnicodeUTF8))
        self.addRadioBF.setText(QtGui.QApplication.translate("MainWindow", "Bifocal", None, QtGui.QApplication.UnicodeUTF8))
        self.addRadioTF.setText(QtGui.QApplication.translate("MainWindow", "Trifocal", None, QtGui.QApplication.UnicodeUTF8))
        self.childGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Monture", None, QtGui.QApplication.UnicodeUTF8))
        self.childRadioNo.setText(QtGui.QApplication.translate("MainWindow", "Adulte", None, QtGui.QApplication.UnicodeUTF8))
        self.childRadioYes.setText(QtGui.QApplication.translate("MainWindow", "Enfant", None, QtGui.QApplication.UnicodeUTF8))
        self.solarGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Teinte", None, QtGui.QApplication.UnicodeUTF8))
        self.solarRadioNo.setText(QtGui.QApplication.translate("MainWindow", "Non teinté (T1, T2)", None, QtGui.QApplication.UnicodeUTF8))
        self.solarRadioYes.setText(QtGui.QApplication.translate("MainWindow", "Teinté (T3, T4)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Commentaire :", None, QtGui.QApplication.UnicodeUTF8))
        self.fileMenu.setTitle(QtGui.QApplication.translate("MainWindow", "Fichier", None, QtGui.QApplication.UnicodeUTF8))
        self.newAction.setText(QtGui.QApplication.translate("MainWindow", "Nouveau", None, QtGui.QApplication.UnicodeUTF8))
        self.newAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAction.setText(QtGui.QApplication.translate("MainWindow", "Enregistrer", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.exitAction.setText(QtGui.QApplication.translate("MainWindow", "Quitter", None, QtGui.QApplication.UnicodeUTF8))
        self.exitAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))

from anglespinbox import angleSpinBox
from negativezerospinbox import negativeZeroSpinBox
from dotspinbox import dotSpinBox

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

