# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inventory.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 636)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("glasses.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.mainLayout = QtWidgets.QVBoxLayout()
        self.mainLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.mainLayout.setSpacing(6)
        self.mainLayout.setObjectName("mainLayout")
        self.numberingLayout = QtWidgets.QHBoxLayout()
        self.numberingLayout.setObjectName("numberingLayout")
        self.eyeglassesNum = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.eyeglassesNum.setFont(font)
        self.eyeglassesNum.setMinimum(1)
        self.eyeglassesNum.setMaximum(1000000)
        self.eyeglassesNum.setProperty("value", 1)
        self.eyeglassesNum.setObjectName("eyeglassesNum")
        self.numberingLayout.addWidget(self.eyeglassesNum)
        self.status = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.status.setFont(font)
        self.status.setObjectName("status")
        self.numberingLayout.addWidget(self.status)
        self.newButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.newButton.setFont(font)
        self.newButton.setObjectName("newButton")
        self.numberingLayout.addWidget(self.newButton)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.saveButton.setFont(font)
        self.saveButton.setObjectName("saveButton")
        self.numberingLayout.addWidget(self.saveButton)
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.deleteButton.setObjectName("deleteButton")
        self.numberingLayout.addWidget(self.deleteButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.numberingLayout.addItem(spacerItem)
        self.backupButton = QtWidgets.QPushButton(self.centralwidget)
        self.backupButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.backupButton.setObjectName("backupButton")
        self.numberingLayout.addWidget(self.backupButton)
        self.restoreButton = QtWidgets.QPushButton(self.centralwidget)
        self.restoreButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.restoreButton.setObjectName("restoreButton")
        self.numberingLayout.addWidget(self.restoreButton)
        self.mainLayout.addLayout(self.numberingLayout)
        self.eyesLayout = QtWidgets.QHBoxLayout()
        self.eyesLayout.setObjectName("eyesLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.eyesLayout.addItem(spacerItem1)
        self.rightEyeGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.rightEyeGroupBox.setFont(font)
        self.rightEyeGroupBox.setObjectName("rightEyeGroupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.rightEyeGroupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.rightEyeLayout = QtWidgets.QGridLayout()
        self.rightEyeLayout.setObjectName("rightEyeLayout")
        self.label_2 = QtWidgets.QLabel(self.rightEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.rightEyeLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.rightEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.rightEyeLayout.addWidget(self.label_5, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.rightEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.rightEyeLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.rAxisSpin = angleSpinBox(self.rightEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rAxisSpin.setFont(font)
        self.rAxisSpin.setWrapping(True)
        self.rAxisSpin.setMinimum(5)
        self.rAxisSpin.setMaximum(180)
        self.rAxisSpin.setSingleStep(5)
        self.rAxisSpin.setProperty("value", 180)
        self.rAxisSpin.setObjectName("rAxisSpin")
        self.rightEyeLayout.addWidget(self.rAxisSpin, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.rightEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.rightEyeLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.rLinkCheckbox = QtWidgets.QCheckBox(self.rightEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.rLinkCheckbox.setFont(font)
        self.rLinkCheckbox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.rLinkCheckbox.setObjectName("rLinkCheckbox")
        self.rightEyeLayout.addWidget(self.rLinkCheckbox, 2, 3, 1, 1)
        self.rAddSpin = dotSpinBox(self.rightEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rAddSpin.setFont(font)
        self.rAddSpin.setObjectName("rAddSpin")
        self.rightEyeLayout.addWidget(self.rAddSpin, 1, 3, 1, 1)
        self.rCylSpin = negativeZeroSpinBox(self.rightEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rCylSpin.setFont(font)
        self.rCylSpin.setObjectName("rCylSpin")
        self.rightEyeLayout.addWidget(self.rCylSpin, 1, 1, 1, 1)
        self.rSphereSpin = dotSpinBox(self.rightEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rSphereSpin.setFont(font)
        self.rSphereSpin.setObjectName("rSphereSpin")
        self.rightEyeLayout.addWidget(self.rSphereSpin, 1, 0, 1, 1)
        self.rLabelCylPos = QtWidgets.QLabel(self.rightEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.rLabelCylPos.setFont(font)
        self.rLabelCylPos.setObjectName("rLabelCylPos")
        self.rightEyeLayout.addWidget(self.rLabelCylPos, 2, 1, 1, 1)
        self.gridLayout_7.addLayout(self.rightEyeLayout, 0, 0, 1, 1)
        self.eyesLayout.addWidget(self.rightEyeGroupBox)
        self.leftEyeGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.leftEyeGroupBox.setFont(font)
        self.leftEyeGroupBox.setObjectName("leftEyeGroupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.leftEyeGroupBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.leftEyeLayout = QtWidgets.QGridLayout()
        self.leftEyeLayout.setObjectName("leftEyeLayout")
        self.label_8 = QtWidgets.QLabel(self.leftEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.leftEyeLayout.addWidget(self.label_8, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.leftEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.leftEyeLayout.addWidget(self.label_9, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.leftEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.leftEyeLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.lAxisSpin = angleSpinBox(self.leftEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lAxisSpin.setFont(font)
        self.lAxisSpin.setWrapping(True)
        self.lAxisSpin.setMinimum(5)
        self.lAxisSpin.setMaximum(180)
        self.lAxisSpin.setSingleStep(5)
        self.lAxisSpin.setProperty("value", 180)
        self.lAxisSpin.setObjectName("lAxisSpin")
        self.leftEyeLayout.addWidget(self.lAxisSpin, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.leftEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.leftEyeLayout.addWidget(self.label_7, 0, 3, 1, 1)
        self.lLinkCheckbox = QtWidgets.QCheckBox(self.leftEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lLinkCheckbox.setFont(font)
        self.lLinkCheckbox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lLinkCheckbox.setObjectName("lLinkCheckbox")
        self.leftEyeLayout.addWidget(self.lLinkCheckbox, 2, 3, 1, 1)
        self.lSphereSpin = dotSpinBox(self.leftEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lSphereSpin.setFont(font)
        self.lSphereSpin.setObjectName("lSphereSpin")
        self.leftEyeLayout.addWidget(self.lSphereSpin, 1, 0, 1, 1)
        self.lCylSpin = negativeZeroSpinBox(self.leftEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lCylSpin.setFont(font)
        self.lCylSpin.setObjectName("lCylSpin")
        self.leftEyeLayout.addWidget(self.lCylSpin, 1, 1, 1, 1)
        self.lAddSpin = dotSpinBox(self.leftEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lAddSpin.setFont(font)
        self.lAddSpin.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.lAddSpin.setObjectName("lAddSpin")
        self.leftEyeLayout.addWidget(self.lAddSpin, 1, 3, 1, 1)
        self.lLabelCylPos = QtWidgets.QLabel(self.leftEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lLabelCylPos.setFont(font)
        self.lLabelCylPos.setObjectName("lLabelCylPos")
        self.leftEyeLayout.addWidget(self.lLabelCylPos, 2, 1, 1, 1)
        self.gridLayout_8.addLayout(self.leftEyeLayout, 0, 0, 1, 1)
        self.eyesLayout.addWidget(self.leftEyeGroupBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.eyesLayout.addItem(spacerItem2)
        self.mainLayout.addLayout(self.eyesLayout)
        self.otherLayout = QtWidgets.QHBoxLayout()
        self.otherLayout.setObjectName("otherLayout")
        self.optionsLayout = QtWidgets.QVBoxLayout()
        self.optionsLayout.setObjectName("optionsLayout")
        self.addGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.addGroupBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addGroupBox.sizePolicy().hasHeightForWidth())
        self.addGroupBox.setSizePolicy(sizePolicy)
        self.addGroupBox.setObjectName("addGroupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.addGroupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.addLayout = QtWidgets.QVBoxLayout()
        self.addLayout.setObjectName("addLayout")
        self.addRadioP = QtWidgets.QRadioButton(self.addGroupBox)
        self.addRadioP.setChecked(True)
        self.addRadioP.setObjectName("addRadioP")
        self.addLayout.addWidget(self.addRadioP)
        self.addRadioBF = QtWidgets.QRadioButton(self.addGroupBox)
        self.addRadioBF.setObjectName("addRadioBF")
        self.addLayout.addWidget(self.addRadioBF)
        self.gridLayout_9.addLayout(self.addLayout, 1, 0, 1, 1)
        self.optionsLayout.addWidget(self.addGroupBox)
        self.childGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.childGroupBox.sizePolicy().hasHeightForWidth())
        self.childGroupBox.setSizePolicy(sizePolicy)
        self.childGroupBox.setObjectName("childGroupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.childGroupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.childRadioYes = QtWidgets.QRadioButton(self.childGroupBox)
        self.childRadioYes.setObjectName("childRadioYes")
        self.gridLayout_5.addWidget(self.childRadioYes, 5, 0, 1, 1)
        self.childRadioNo = QtWidgets.QRadioButton(self.childGroupBox)
        self.childRadioNo.setChecked(True)
        self.childRadioNo.setObjectName("childRadioNo")
        self.gridLayout_5.addWidget(self.childRadioNo, 3, 0, 1, 1)
        self.childRadioHalf = QtWidgets.QRadioButton(self.childGroupBox)
        self.childRadioHalf.setObjectName("childRadioHalf")
        self.gridLayout_5.addWidget(self.childRadioHalf, 4, 0, 1, 1)
        self.optionsLayout.addWidget(self.childGroupBox)
        self.solarGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.solarGroupBox.sizePolicy().hasHeightForWidth())
        self.solarGroupBox.setSizePolicy(sizePolicy)
        self.solarGroupBox.setObjectName("solarGroupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.solarGroupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.solarRadioNo = QtWidgets.QRadioButton(self.solarGroupBox)
        self.solarRadioNo.setChecked(True)
        self.solarRadioNo.setObjectName("solarRadioNo")
        self.gridLayout_6.addWidget(self.solarRadioNo, 0, 0, 1, 1)
        self.solarRadioYes = QtWidgets.QRadioButton(self.solarGroupBox)
        self.solarRadioYes.setObjectName("solarRadioYes")
        self.gridLayout_6.addWidget(self.solarRadioYes, 1, 0, 1, 1)
        self.optionsLayout.addWidget(self.solarGroupBox)
        self.otherLayout.addLayout(self.optionsLayout)
        self.commentLayout = QtWidgets.QVBoxLayout()
        self.commentLayout.setObjectName("commentLayout")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.commentLayout.addWidget(self.label_10)
        self.commentEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commentEdit.sizePolicy().hasHeightForWidth())
        self.commentEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.commentEdit.setFont(font)
        self.commentEdit.setTabChangesFocus(True)
        self.commentEdit.setBackgroundVisible(False)
        self.commentEdit.setObjectName("commentEdit")
        self.commentLayout.addWidget(self.commentEdit)
        self.otherLayout.addLayout(self.commentLayout)
        self.mainLayout.addLayout(self.otherLayout)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setVisible(False)
        self.tableView.verticalHeader().setStretchLastSection(False)
        self.mainLayout.addWidget(self.tableView)
        self.gridLayout_3.addLayout(self.mainLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 21))
        self.menubar.setObjectName("menubar")
        self.fileMenu = QtWidgets.QMenu(self.menubar)
        self.fileMenu.setObjectName("fileMenu")
        MainWindow.setMenuBar(self.menubar)
        self.newAction = QtWidgets.QAction(MainWindow)
        self.newAction.setObjectName("newAction")
        self.saveAction = QtWidgets.QAction(MainWindow)
        self.saveAction.setObjectName("saveAction")
        self.exitAction = QtWidgets.QAction(MainWindow)
        self.exitAction.setObjectName("exitAction")
        self.backupAction = QtWidgets.QAction(MainWindow)
        self.backupAction.setObjectName("backupAction")
        self.restoreAction = QtWidgets.QAction(MainWindow)
        self.restoreAction.setObjectName("restoreAction")
        self.deleteAction = QtWidgets.QAction(MainWindow)
        self.deleteAction.setObjectName("deleteAction")
        self.printAction = QtWidgets.QAction(MainWindow)
        self.printAction.setObjectName("printAction")
        self.fileMenu.addAction(self.newAction)
        self.fileMenu.addAction(self.saveAction)
        self.fileMenu.addAction(self.deleteAction)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.backupAction)
        self.fileMenu.addAction(self.restoreAction)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.printAction)
        self.fileMenu.addAction(self.exitAction)
        self.menubar.addAction(self.fileMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.newButton, self.eyeglassesNum)
        MainWindow.setTabOrder(self.eyeglassesNum, self.rSphereSpin)
        MainWindow.setTabOrder(self.rSphereSpin, self.rCylSpin)
        MainWindow.setTabOrder(self.rCylSpin, self.rAxisSpin)
        MainWindow.setTabOrder(self.rAxisSpin, self.rAddSpin)
        MainWindow.setTabOrder(self.rAddSpin, self.lSphereSpin)
        MainWindow.setTabOrder(self.lSphereSpin, self.lCylSpin)
        MainWindow.setTabOrder(self.lCylSpin, self.lAxisSpin)
        MainWindow.setTabOrder(self.lAxisSpin, self.lAddSpin)
        MainWindow.setTabOrder(self.lAddSpin, self.addRadioP)
        MainWindow.setTabOrder(self.addRadioP, self.addRadioBF)
        MainWindow.setTabOrder(self.addRadioBF, self.childRadioNo)
        MainWindow.setTabOrder(self.childRadioNo, self.childRadioYes)
        MainWindow.setTabOrder(self.childRadioYes, self.solarRadioNo)
        MainWindow.setTabOrder(self.solarRadioNo, self.solarRadioYes)
        MainWindow.setTabOrder(self.solarRadioYes, self.commentEdit)
        MainWindow.setTabOrder(self.commentEdit, self.saveButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Oryx Optical DBSM - Inventory"))
        self.status.setText(_translate("MainWindow", "Empty"))
        self.newButton.setText(_translate("MainWindow", "Nouvelle paire"))
        self.saveButton.setText(_translate("MainWindow", "Enregistrer"))
        self.deleteButton.setText(_translate("MainWindow", "Supprimer"))
        self.backupButton.setText(_translate("MainWindow", "Backup"))
        self.restoreButton.setText(_translate("MainWindow", "Restaurer"))
        self.rightEyeGroupBox.setTitle(_translate("MainWindow", "OD (Œil Droit)"))
        self.label_2.setText(_translate("MainWindow", "Sphere"))
        self.label_5.setText(_translate("MainWindow", "Addition"))
        self.label_4.setText(_translate("MainWindow", "Axe"))
        self.label_3.setText(_translate("MainWindow", "Cylindre"))
        self.rLinkCheckbox.setText(_translate("MainWindow", "Lié"))
        self.rLabelCylPos.setToolTip(_translate("MainWindow", "Le cylindre indiqué est positif, une conversion sera effectuée lors de la Sauvegarde"))
        self.rLabelCylPos.setText(_translate("MainWindow", "Cylindre positif"))
        self.leftEyeGroupBox.setTitle(_translate("MainWindow", "OG (Œil Gauche)"))
        self.label_8.setText(_translate("MainWindow", "Axe"))
        self.label_9.setText(_translate("MainWindow", "Cylindre"))
        self.label_6.setText(_translate("MainWindow", "Sphere"))
        self.label_7.setText(_translate("MainWindow", "Addition"))
        self.lLinkCheckbox.setText(_translate("MainWindow", "Lié"))
        self.lLabelCylPos.setToolTip(_translate("MainWindow", "Le cylindre indiqué est positif, une conversion sera effectuée lors de la Sauvegarde"))
        self.lLabelCylPos.setText(_translate("MainWindow", "Cylindre positif"))
        self.addGroupBox.setTitle(_translate("MainWindow", "Multifocal"))
        self.addRadioP.setText(_translate("MainWindow", "Progressif"))
        self.addRadioBF.setText(_translate("MainWindow", "Bifocal"))
        self.childGroupBox.setTitle(_translate("MainWindow", "Monture"))
        self.childRadioYes.setText(_translate("MainWindow", "Enfant"))
        self.childRadioNo.setText(_translate("MainWindow", "Adulte"))
        self.childRadioHalf.setText(_translate("MainWindow", "Demi-lunes"))
        self.solarGroupBox.setTitle(_translate("MainWindow", "Teinte"))
        self.solarRadioNo.setText(_translate("MainWindow", "Non teintés (ou T1, T2)"))
        self.solarRadioYes.setText(_translate("MainWindow", "Teintés (Photochromiques ou T3, T4)"))
        self.label_10.setText(_translate("MainWindow", "Commentaire :"))
        self.fileMenu.setTitle(_translate("MainWindow", "Fichier"))
        self.newAction.setText(_translate("MainWindow", "Nouveau"))
        self.newAction.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.saveAction.setText(_translate("MainWindow", "Sauvegarder"))
        self.saveAction.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.exitAction.setText(_translate("MainWindow", "Quitter"))
        self.exitAction.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.backupAction.setText(_translate("MainWindow", "Backup"))
        self.backupAction.setToolTip(_translate("MainWindow", "Sauvegarde la base de donnée dans un fichier externe"))
        self.backupAction.setShortcut(_translate("MainWindow", "Ctrl+Shift+B"))
        self.restoreAction.setText(_translate("MainWindow", "Restaurer"))
        self.restoreAction.setToolTip(_translate("MainWindow", "Charge un Backup. Attention, les données actuellement affichées sont détruites !"))
        self.restoreAction.setShortcut(_translate("MainWindow", "Ctrl+Shift+R"))
        self.deleteAction.setText(_translate("MainWindow", "Supprimer"))
        self.deleteAction.setToolTip(_translate("MainWindow", "Supprimer les lunettes sélectionnées"))
        self.deleteAction.setShortcut(_translate("MainWindow", "Ctrl+Shift+D"))
        self.printAction.setText(_translate("MainWindow", "Imprimer..."))
        self.printAction.setToolTip(_translate("MainWindow", "Crée un fichier PDF contenant la liste des lunettes triées"))


from anglespinbox import angleSpinBox
from dotspinbox import dotSpinBox
from negativezerospinbox import negativeZeroSpinBox
