# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search.ui'
#
# Created: Fri Sep 27 10:38:58 2013
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(798, 641)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("glasses.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.mainLayout = QtGui.QVBoxLayout()
        self.mainLayout.setSpacing(6)
        self.mainLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.mainLayout.setObjectName(_fromUtf8("mainLayout"))
        self.eyesLayout = QtGui.QHBoxLayout()
        self.eyesLayout.setObjectName(_fromUtf8("eyesLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.eyesLayout.addItem(spacerItem)
        self.rightEyeGroupBox = QtGui.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.rightEyeGroupBox.setFont(font)
        self.rightEyeGroupBox.setObjectName(_fromUtf8("rightEyeGroupBox"))
        self.gridLayout_7 = QtGui.QGridLayout(self.rightEyeGroupBox)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.rightEyeLayout = QtGui.QGridLayout()
        self.rightEyeLayout.setObjectName(_fromUtf8("rightEyeLayout"))
        self.label_2 = QtGui.QLabel(self.rightEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.rightEyeLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.rightEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.rightEyeLayout.addWidget(self.label_5, 0, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.rightEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.rightEyeLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.rAxisSpin = angleSpinBox(self.rightEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rAxisSpin.setFont(font)
        self.rAxisSpin.setWrapping(True)
        self.rAxisSpin.setMinimum(5)
        self.rAxisSpin.setMaximum(180)
        self.rAxisSpin.setSingleStep(5)
        self.rAxisSpin.setProperty("value", 180)
        self.rAxisSpin.setObjectName(_fromUtf8("rAxisSpin"))
        self.rightEyeLayout.addWidget(self.rAxisSpin, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.rightEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.rightEyeLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.rLinkCheckbox = QtGui.QCheckBox(self.rightEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.rLinkCheckbox.setFont(font)
        self.rLinkCheckbox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.rLinkCheckbox.setChecked(True)
        self.rLinkCheckbox.setObjectName(_fromUtf8("rLinkCheckbox"))
        self.rightEyeLayout.addWidget(self.rLinkCheckbox, 2, 3, 1, 1)
        self.rAddSpin = dotSpinBox(self.rightEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rAddSpin.setFont(font)
        self.rAddSpin.setObjectName(_fromUtf8("rAddSpin"))
        self.rightEyeLayout.addWidget(self.rAddSpin, 1, 3, 1, 1)
        self.rCylSpin = negativeZeroSpinBox(self.rightEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rCylSpin.setFont(font)
        self.rCylSpin.setObjectName(_fromUtf8("rCylSpin"))
        self.rightEyeLayout.addWidget(self.rCylSpin, 1, 1, 1, 1)
        self.rSphereSpin = dotSpinBox(self.rightEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rSphereSpin.setFont(font)
        self.rSphereSpin.setObjectName(_fromUtf8("rSphereSpin"))
        self.rightEyeLayout.addWidget(self.rSphereSpin, 1, 0, 1, 1)
        self.rLabelCylPos = QtGui.QLabel(self.rightEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.rLabelCylPos.setFont(font)
        self.rLabelCylPos.setObjectName(_fromUtf8("rLabelCylPos"))
        self.rightEyeLayout.addWidget(self.rLabelCylPos, 2, 1, 1, 1)
        self.gridLayout_7.addLayout(self.rightEyeLayout, 1, 0, 1, 1)
        self.rMasterRadio = QtGui.QRadioButton(self.rightEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rMasterRadio.setFont(font)
        self.rMasterRadio.setChecked(True)
        self.rMasterRadio.setObjectName(_fromUtf8("rMasterRadio"))
        self.buttonGroup = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.rMasterRadio)
        self.gridLayout_7.addWidget(self.rMasterRadio, 0, 0, 1, 1)
        self.eyesLayout.addWidget(self.rightEyeGroupBox)
        self.leftEyeGroupBox = QtGui.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.leftEyeGroupBox.setFont(font)
        self.leftEyeGroupBox.setObjectName(_fromUtf8("leftEyeGroupBox"))
        self.gridLayout_8 = QtGui.QGridLayout(self.leftEyeGroupBox)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.leftEyeLayout = QtGui.QGridLayout()
        self.leftEyeLayout.setObjectName(_fromUtf8("leftEyeLayout"))
        self.lCylSpin = negativeZeroSpinBox(self.leftEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lCylSpin.setFont(font)
        self.lCylSpin.setObjectName(_fromUtf8("lCylSpin"))
        self.leftEyeLayout.addWidget(self.lCylSpin, 1, 1, 1, 1)
        self.lAddSpin = dotSpinBox(self.leftEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lAddSpin.setFont(font)
        self.lAddSpin.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.lAddSpin.setObjectName(_fromUtf8("lAddSpin"))
        self.leftEyeLayout.addWidget(self.lAddSpin, 1, 3, 1, 1)
        self.lLinkCheckbox = QtGui.QCheckBox(self.leftEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lLinkCheckbox.setFont(font)
        self.lLinkCheckbox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lLinkCheckbox.setChecked(True)
        self.lLinkCheckbox.setObjectName(_fromUtf8("lLinkCheckbox"))
        self.leftEyeLayout.addWidget(self.lLinkCheckbox, 2, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.leftEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.leftEyeLayout.addWidget(self.label_8, 0, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.leftEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.leftEyeLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.leftEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.leftEyeLayout.addWidget(self.label_9, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.leftEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.leftEyeLayout.addWidget(self.label_7, 0, 3, 1, 1)
        self.lSphereSpin = dotSpinBox(self.leftEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lSphereSpin.setFont(font)
        self.lSphereSpin.setObjectName(_fromUtf8("lSphereSpin"))
        self.leftEyeLayout.addWidget(self.lSphereSpin, 1, 0, 1, 1)
        self.lAxisSpin = angleSpinBox(self.leftEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lAxisSpin.setFont(font)
        self.lAxisSpin.setWrapping(True)
        self.lAxisSpin.setMinimum(5)
        self.lAxisSpin.setMaximum(180)
        self.lAxisSpin.setSingleStep(5)
        self.lAxisSpin.setProperty("value", 180)
        self.lAxisSpin.setObjectName(_fromUtf8("lAxisSpin"))
        self.leftEyeLayout.addWidget(self.lAxisSpin, 1, 2, 1, 1)
        self.lLabelCylPos = QtGui.QLabel(self.leftEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lLabelCylPos.setFont(font)
        self.lLabelCylPos.setObjectName(_fromUtf8("lLabelCylPos"))
        self.leftEyeLayout.addWidget(self.lLabelCylPos, 2, 1, 1, 1)
        self.gridLayout_8.addLayout(self.leftEyeLayout, 1, 0, 1, 1)
        self.lMasterRadio = QtGui.QRadioButton(self.leftEyeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lMasterRadio.setFont(font)
        self.lMasterRadio.setObjectName(_fromUtf8("lMasterRadio"))
        self.buttonGroup.addButton(self.lMasterRadio)
        self.gridLayout_8.addWidget(self.lMasterRadio, 0, 0, 1, 1)
        self.eyesLayout.addWidget(self.leftEyeGroupBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.eyesLayout.addItem(spacerItem1)
        self.mainLayout.addLayout(self.eyesLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 10, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.childGroupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.childGroupBox.sizePolicy().hasHeightForWidth())
        self.childGroupBox.setSizePolicy(sizePolicy)
        self.childGroupBox.setObjectName(_fromUtf8("childGroupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.childGroupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.childRadioNo = QtGui.QRadioButton(self.childGroupBox)
        self.childRadioNo.setChecked(True)
        self.childRadioNo.setObjectName(_fromUtf8("childRadioNo"))
        self.horizontalLayout_2.addWidget(self.childRadioNo)
        self.childRadioHalf = QtGui.QRadioButton(self.childGroupBox)
        self.childRadioHalf.setObjectName(_fromUtf8("childRadioHalf"))
        self.horizontalLayout_2.addWidget(self.childRadioHalf)
        self.childRadioYes = QtGui.QRadioButton(self.childGroupBox)
        self.childRadioYes.setObjectName(_fromUtf8("childRadioYes"))
        self.horizontalLayout_2.addWidget(self.childRadioYes)
        self.horizontalLayout.addWidget(self.childGroupBox)
        self.solarGroupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.solarGroupBox.sizePolicy().hasHeightForWidth())
        self.solarGroupBox.setSizePolicy(sizePolicy)
        self.solarGroupBox.setObjectName(_fromUtf8("solarGroupBox"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.solarGroupBox)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.solarRadioNo = QtGui.QRadioButton(self.solarGroupBox)
        self.solarRadioNo.setChecked(True)
        self.solarRadioNo.setObjectName(_fromUtf8("solarRadioNo"))
        self.horizontalLayout_3.addWidget(self.solarRadioNo)
        self.solarRadioYes = QtGui.QRadioButton(self.solarGroupBox)
        self.solarRadioYes.setObjectName(_fromUtf8("solarRadioYes"))
        self.horizontalLayout_3.addWidget(self.solarRadioYes)
        self.horizontalLayout.addWidget(self.solarGroupBox)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.mainLayout.addLayout(self.horizontalLayout)
        self.numberingLayout = QtGui.QHBoxLayout()
        self.numberingLayout.setObjectName(_fromUtf8("numberingLayout"))
        self.resetButton = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.resetButton.setFont(font)
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.numberingLayout.addWidget(self.resetButton)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.numberingLayout.addItem(spacerItem4)
        self.searchButton = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.searchButton.setFont(font)
        self.searchButton.setObjectName(_fromUtf8("searchButton"))
        self.numberingLayout.addWidget(self.searchButton)
        self.distantSearchButton = QtGui.QPushButton(self.centralwidget)
        self.distantSearchButton.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.distantSearchButton.setFont(font)
        self.distantSearchButton.setObjectName(_fromUtf8("distantSearchButton"))
        self.numberingLayout.addWidget(self.distantSearchButton)
        self.nearSearchButton = QtGui.QPushButton(self.centralwidget)
        self.nearSearchButton.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.nearSearchButton.setFont(font)
        self.nearSearchButton.setObjectName(_fromUtf8("nearSearchButton"))
        self.numberingLayout.addWidget(self.nearSearchButton)
        self.mainLayout.addLayout(self.numberingLayout)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.mainLayout.addWidget(self.label)
        self.tableView = QtGui.QTableView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setVisible(False)
        self.tableView.verticalHeader().setStretchLastSection(False)
        self.mainLayout.addWidget(self.tableView)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 1, 0, 1, 1)
        self.commentEdit = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commentEdit.sizePolicy().hasHeightForWidth())
        self.commentEdit.setSizePolicy(sizePolicy)
        self.commentEdit.setMaximumSize(QtCore.QSize(16777215, 120))
        self.commentEdit.setReadOnly(True)
        self.commentEdit.setObjectName(_fromUtf8("commentEdit"))
        self.gridLayout.addWidget(self.commentEdit, 0, 3, 5, 2)
        self.eyeglassesNum = QtGui.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.eyeglassesNum.setFont(font)
        self.eyeglassesNum.setMinimum(1)
        self.eyeglassesNum.setMaximum(1000000)
        self.eyeglassesNum.setProperty("value", 1)
        self.eyeglassesNum.setObjectName(_fromUtf8("eyeglassesNum"))
        self.gridLayout.addWidget(self.eyeglassesNum, 0, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 1, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lSphereLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lSphereLabel.sizePolicy().hasHeightForWidth())
        self.lSphereLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lSphereLabel.setFont(font)
        self.lSphereLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lSphereLabel.setObjectName(_fromUtf8("lSphereLabel"))
        self.horizontalLayout_5.addWidget(self.lSphereLabel)
        self.lCylLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lCylLabel.sizePolicy().hasHeightForWidth())
        self.lCylLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lCylLabel.setFont(font)
        self.lCylLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lCylLabel.setObjectName(_fromUtf8("lCylLabel"))
        self.horizontalLayout_5.addWidget(self.lCylLabel)
        self.lAxisLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lAxisLabel.sizePolicy().hasHeightForWidth())
        self.lAxisLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lAxisLabel.setFont(font)
        self.lAxisLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lAxisLabel.setObjectName(_fromUtf8("lAxisLabel"))
        self.horizontalLayout_5.addWidget(self.lAxisLabel)
        self.lAddLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lAddLabel.sizePolicy().hasHeightForWidth())
        self.lAddLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lAddLabel.setFont(font)
        self.lAddLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lAddLabel.setObjectName(_fromUtf8("lAddLabel"))
        self.horizontalLayout_5.addWidget(self.lAddLabel)
        self.gridLayout.addLayout(self.horizontalLayout_5, 2, 2, 1, 1)
        self.removeButton = QtGui.QPushButton(self.centralwidget)
        self.removeButton.setEnabled(False)
        self.removeButton.setObjectName(_fromUtf8("removeButton"))
        self.gridLayout.addWidget(self.removeButton, 4, 0, 1, 1)
        self.addButton = QtGui.QPushButton(self.centralwidget)
        self.addButton.setEnabled(False)
        self.addButton.setObjectName(_fromUtf8("addButton"))
        self.gridLayout.addWidget(self.addButton, 4, 2, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.rSphereLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rSphereLabel.sizePolicy().hasHeightForWidth())
        self.rSphereLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.rSphereLabel.setFont(font)
        self.rSphereLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rSphereLabel.setObjectName(_fromUtf8("rSphereLabel"))
        self.horizontalLayout_4.addWidget(self.rSphereLabel)
        self.rCylLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rCylLabel.sizePolicy().hasHeightForWidth())
        self.rCylLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.rCylLabel.setFont(font)
        self.rCylLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rCylLabel.setObjectName(_fromUtf8("rCylLabel"))
        self.horizontalLayout_4.addWidget(self.rCylLabel)
        self.rAxisLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rAxisLabel.sizePolicy().hasHeightForWidth())
        self.rAxisLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.rAxisLabel.setFont(font)
        self.rAxisLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rAxisLabel.setObjectName(_fromUtf8("rAxisLabel"))
        self.horizontalLayout_4.addWidget(self.rAxisLabel)
        self.rAddLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rAddLabel.sizePolicy().hasHeightForWidth())
        self.rAddLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.rAddLabel.setFont(font)
        self.rAddLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rAddLabel.setObjectName(_fromUtf8("rAddLabel"))
        self.horizontalLayout_4.addWidget(self.rAddLabel)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.frameLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.frameLabel.setFont(font)
        self.frameLabel.setText(_fromUtf8(""))
        self.frameLabel.setObjectName(_fromUtf8("frameLabel"))
        self.horizontalLayout_6.addWidget(self.frameLabel)
        self.solarLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.solarLabel.setFont(font)
        self.solarLabel.setText(_fromUtf8(""))
        self.solarLabel.setObjectName(_fromUtf8("solarLabel"))
        self.horizontalLayout_6.addWidget(self.solarLabel)
        self.addLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addLabel.setFont(font)
        self.addLabel.setText(_fromUtf8(""))
        self.addLabel.setObjectName(_fromUtf8("addLabel"))
        self.horizontalLayout_6.addWidget(self.addLabel)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_6, 3, 0, 1, 3)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 1, 2, 1)
        self.mainLayout.addLayout(self.gridLayout)
        self.gridLayout_3.addLayout(self.mainLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.fileMenu = QtGui.QMenu(self.menubar)
        self.fileMenu.setObjectName(_fromUtf8("fileMenu"))
        MainWindow.setMenuBar(self.menubar)
        self.exitAction = QtGui.QAction(MainWindow)
        self.exitAction.setObjectName(_fromUtf8("exitAction"))
        self.searchAction = QtGui.QAction(MainWindow)
        self.searchAction.setObjectName(_fromUtf8("searchAction"))
        self.resetAction = QtGui.QAction(MainWindow)
        self.resetAction.setObjectName(_fromUtf8("resetAction"))
        self.distantSearchAction = QtGui.QAction(MainWindow)
        self.distantSearchAction.setObjectName(_fromUtf8("distantSearchAction"))
        self.nearSearchAction = QtGui.QAction(MainWindow)
        self.nearSearchAction.setObjectName(_fromUtf8("nearSearchAction"))
        self.fileMenu.addAction(self.searchAction)
        self.fileMenu.addAction(self.distantSearchAction)
        self.fileMenu.addAction(self.nearSearchAction)
        self.fileMenu.addAction(self.resetAction)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.exitAction)
        self.menubar.addAction(self.fileMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.rMasterRadio, self.lMasterRadio)
        MainWindow.setTabOrder(self.lMasterRadio, self.rSphereSpin)
        MainWindow.setTabOrder(self.rSphereSpin, self.rCylSpin)
        MainWindow.setTabOrder(self.rCylSpin, self.rAxisSpin)
        MainWindow.setTabOrder(self.rAxisSpin, self.rAddSpin)
        MainWindow.setTabOrder(self.rAddSpin, self.lSphereSpin)
        MainWindow.setTabOrder(self.lSphereSpin, self.lCylSpin)
        MainWindow.setTabOrder(self.lCylSpin, self.lAxisSpin)
        MainWindow.setTabOrder(self.lAxisSpin, self.lAddSpin)
        MainWindow.setTabOrder(self.lAddSpin, self.childRadioNo)
        MainWindow.setTabOrder(self.childRadioNo, self.childRadioHalf)
        MainWindow.setTabOrder(self.childRadioHalf, self.childRadioYes)
        MainWindow.setTabOrder(self.childRadioYes, self.solarRadioNo)
        MainWindow.setTabOrder(self.solarRadioNo, self.solarRadioYes)
        MainWindow.setTabOrder(self.solarRadioYes, self.searchButton)
        MainWindow.setTabOrder(self.searchButton, self.distantSearchButton)
        MainWindow.setTabOrder(self.distantSearchButton, self.nearSearchButton)
        MainWindow.setTabOrder(self.nearSearchButton, self.tableView)
        MainWindow.setTabOrder(self.tableView, self.resetButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Oryx Optical DBSM - Search", None, QtGui.QApplication.UnicodeUTF8))
        self.rightEyeGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "OD (Œil Droit)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Sphere", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Addition", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Axe", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Cylindre", None, QtGui.QApplication.UnicodeUTF8))
        self.rLinkCheckbox.setText(QtGui.QApplication.translate("MainWindow", "Lié", None, QtGui.QApplication.UnicodeUTF8))
        self.rLabelCylPos.setToolTip(QtGui.QApplication.translate("MainWindow", "Le cylindre indiqué est positif, une conversion sera effectuée lors de la Recherche", None, QtGui.QApplication.UnicodeUTF8))
        self.rLabelCylPos.setText(QtGui.QApplication.translate("MainWindow", "Cylindre positif", None, QtGui.QApplication.UnicodeUTF8))
        self.rMasterRadio.setText(QtGui.QApplication.translate("MainWindow", "Œil droit directeur", None, QtGui.QApplication.UnicodeUTF8))
        self.leftEyeGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "OG (Œil Gauche)", None, QtGui.QApplication.UnicodeUTF8))
        self.lLinkCheckbox.setText(QtGui.QApplication.translate("MainWindow", "Lié", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Axe", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Sphere", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Cylindre", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Addition", None, QtGui.QApplication.UnicodeUTF8))
        self.lLabelCylPos.setToolTip(QtGui.QApplication.translate("MainWindow", "Le cylindre indiqué est positif, une conversion sera effectuée lors de la Recherche", None, QtGui.QApplication.UnicodeUTF8))
        self.lLabelCylPos.setText(QtGui.QApplication.translate("MainWindow", "Cylindre positif", None, QtGui.QApplication.UnicodeUTF8))
        self.lMasterRadio.setText(QtGui.QApplication.translate("MainWindow", "Œil gauche directeur", None, QtGui.QApplication.UnicodeUTF8))
        self.childGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Monture", None, QtGui.QApplication.UnicodeUTF8))
        self.childRadioNo.setText(QtGui.QApplication.translate("MainWindow", "Adulte", None, QtGui.QApplication.UnicodeUTF8))
        self.childRadioHalf.setText(QtGui.QApplication.translate("MainWindow", "Demi-lune", None, QtGui.QApplication.UnicodeUTF8))
        self.childRadioYes.setText(QtGui.QApplication.translate("MainWindow", "Enfant", None, QtGui.QApplication.UnicodeUTF8))
        self.solarGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Teinte", None, QtGui.QApplication.UnicodeUTF8))
        self.solarRadioNo.setText(QtGui.QApplication.translate("MainWindow", "Non teintés (ou T1, T2)", None, QtGui.QApplication.UnicodeUTF8))
        self.solarRadioYes.setText(QtGui.QApplication.translate("MainWindow", "Teintés (Photochromiques ou T3, T4)", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButton.setText(QtGui.QApplication.translate("MainWindow", "Remise à zéro", None, QtGui.QApplication.UnicodeUTF8))
        self.searchButton.setText(QtGui.QApplication.translate("MainWindow", "Rechercher", None, QtGui.QApplication.UnicodeUTF8))
        self.distantSearchButton.setText(QtGui.QApplication.translate("MainWindow", "Vision de loin", None, QtGui.QApplication.UnicodeUTF8))
        self.nearSearchButton.setText(QtGui.QApplication.translate("MainWindow", "Vision de près", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Résultat de la recherche", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "OD (Œil Droit)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "OG (Œil Gauche)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Lunettes numéro :", None, QtGui.QApplication.UnicodeUTF8))
        self.lSphereLabel.setText(QtGui.QApplication.translate("MainWindow", "0.00", None, QtGui.QApplication.UnicodeUTF8))
        self.lCylLabel.setText(QtGui.QApplication.translate("MainWindow", "(-0.00)", None, QtGui.QApplication.UnicodeUTF8))
        self.lAxisLabel.setText(QtGui.QApplication.translate("MainWindow", "180°", None, QtGui.QApplication.UnicodeUTF8))
        self.lAddLabel.setText(QtGui.QApplication.translate("MainWindow", "0.00", None, QtGui.QApplication.UnicodeUTF8))
        self.removeButton.setText(QtGui.QApplication.translate("MainWindow", "Sortir du Stock", None, QtGui.QApplication.UnicodeUTF8))
        self.addButton.setText(QtGui.QApplication.translate("MainWindow", "Remettre en Stock", None, QtGui.QApplication.UnicodeUTF8))
        self.rSphereLabel.setText(QtGui.QApplication.translate("MainWindow", "0.00", None, QtGui.QApplication.UnicodeUTF8))
        self.rCylLabel.setText(QtGui.QApplication.translate("MainWindow", "(-0.00)", None, QtGui.QApplication.UnicodeUTF8))
        self.rAxisLabel.setText(QtGui.QApplication.translate("MainWindow", "180°", None, QtGui.QApplication.UnicodeUTF8))
        self.rAddLabel.setText(QtGui.QApplication.translate("MainWindow", "0.00", None, QtGui.QApplication.UnicodeUTF8))
        self.fileMenu.setTitle(QtGui.QApplication.translate("MainWindow", "Fichier", None, QtGui.QApplication.UnicodeUTF8))
        self.exitAction.setText(QtGui.QApplication.translate("MainWindow", "Quitter", None, QtGui.QApplication.UnicodeUTF8))
        self.exitAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.searchAction.setText(QtGui.QApplication.translate("MainWindow", "Rechercher", None, QtGui.QApplication.UnicodeUTF8))
        self.searchAction.setToolTip(QtGui.QApplication.translate("MainWindow", "Lance la recherche", None, QtGui.QApplication.UnicodeUTF8))
        self.searchAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.resetAction.setText(QtGui.QApplication.translate("MainWindow", "Remise à zéro", None, QtGui.QApplication.UnicodeUTF8))
        self.resetAction.setToolTip(QtGui.QApplication.translate("MainWindow", "Remise à zéro du formulaire de recherche", None, QtGui.QApplication.UnicodeUTF8))
        self.resetAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.distantSearchAction.setText(QtGui.QApplication.translate("MainWindow", "Rechercher vision de loin", None, QtGui.QApplication.UnicodeUTF8))
        self.distantSearchAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))
        self.nearSearchAction.setText(QtGui.QApplication.translate("MainWindow", "Rechercher vision de près", None, QtGui.QApplication.UnicodeUTF8))
        self.nearSearchAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))

from anglespinbox import angleSpinBox
from negativezerospinbox import negativeZeroSpinBox
from dotspinbox import dotSpinBox

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

